name: El Rey del Once
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#444533'
    - '#12110d'
    - '#b5c0b0'
    - '#cda529'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.42199051287025213
  rhythmicContrast: 0.75
purpose: []
